# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

workspace 'Unity-iPhone.xcworkspace'

abstract_target 'Unity-iPhone' do
    pod 'mopub-ios-sdk'
    target 'Unity-iPhone' do
        project 'Unity-iPhone.xcodeproj'
    end
end

